services:
  postgres:
    image: postgres:16-alpine
    container_name: eigen_library_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: eigen
      POSTGRES_PASSWORD: eigen
      POSTGRES_DB: eigen_library
    ports:
      - "5433:5432"
    volumes:
      - eigen_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eigen -d eigen_library"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  eigen_pg_data:
